#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace CentaurFactory.MySqlPRovider	
{
	public partial class CentaurFactoryModel : OpenAccessContext, ICentaurFactoryModelUnitOfWork
	{
		private static string connectionStringName = @"CentaurFactory";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = new CentaurFactoryModelMetadataSource();
		
		public CentaurFactoryModel()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public CentaurFactoryModel(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public CentaurFactoryModel(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public CentaurFactoryModel(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public CentaurFactoryModel(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MySql";
			backend.ProviderName = "MySql.Data.MySqlClient";
		
			CustomizeBackendConfiguration(ref backend);
		
			return backend;
		}

        public IQueryable<Sale> Sales
        {
            get
            {
                return this.GetAll<Sale>();
            }
        }

        public IQueryable<DishReport> DishReport
        {
            get
            {
                return this.GetAll<DishReport>();
            }
        }
		
		/// <summary>
		/// Allows you to customize the BackendConfiguration of CentaurFactoryModel.
		/// </summary>
		/// <param name="config">The BackendConfiguration of CentaurFactoryModel.</param>
		static partial void CustomizeBackendConfiguration(ref BackendConfiguration config);
		
	}
	
	public interface ICentaurFactoryModelUnitOfWork : IUnitOfWork
	{
	}
}
#pragma warning restore 1591
